@url = {{BASE_URL}}/checkout

### Get payments
GET {{url}}/payments

### Get installments
GET {{url}}/installments?paymentId=payment-id&productId=product-id&productPrice=99.90

### Create checkout link
POST {{url}}/link
Content-Type: application/json

{
  "skuTokens": ["sku-token"],
  "quantities": [1]
}
