default_platform(:android)

platform :android do
  desc "Upload AAB to Internal testing"
  lane :internal do
    supply(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
