name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: EAS Token
        run: echo "EAS Token - ${{ secrets.EAS_TOKEN }}"

      - name: EAS setup
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EAS_TOKEN }}

      - name: Build
        run: eas build --platform android --profile devClient --non-interactive --no-wait
