name: CD

on:
  push:
    tags:
      - "*"

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: EAS setup
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EAS_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Google Play API key JSON generation
        env:
          GOOGLE_PLAY_API_KEY: ${{ secrets.GOOGLE_PLAY_API_KEY }}
        run: |
          echo $GOOGLE_PLAY_API_KEY > google-play-api-key.base64
          base64 -d -i google-play-api-key.base64 > google-play-api-key.json

      - name: Build and submit
        run: eas build --platform android --profile production --non-interactive --auto-submit-with-profile=deploy --no-wait
