export const ENDPOINTS = {
  collection: 'collections',
  customer: 'customers',
  banner: 'banners',
  product: 'products',
  clients: 'clients',
  category: 'categories',
  variation: 'variations',
  skus: 'skus',
  brand: 'brands',
  similar: 'similars',
  comment: 'comments',
  lead: 'leads',
  review: 'reviews',
  discount: 'progressive-discounts',
}
